import "@ai-starter/ui/globals.css";

import { cn } from "@ai-starter/ui/lib/utils";
import type { Metadata } from "next";
import { Geist as FontSans, Geist_Mono as FontMono } from "next/font/google";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

const fontMono = FontMono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          fontSans.variable,
          fontMono.variable,
          "min-h-screen bg-background antialiased",
        )}
      >
        {children}
      </body>
    </html>
  );
}
